=== c1ra/xmlDemo/dtd2.dtd
<!ELEMENT adresar (osoba | kompanija)+ >
<!ELEMENT osoba (punoIme, datumRodjenja, adresa, telefon, email+)>
  <!ELEMENT punoIme (ime, srednjeIme?,prezime+)>
    <!ELEMENT ime (#PCDATA)>
    <!ELEMENT srednjeIme (#PCDATA)>
    <!ELEMENT prezime (#PCDATA)>
  <!ELEMENT datumRodjenja (dan, mesec, godina)>
    <!ELEMENT dan (#PCDATA)>
    <!ELEMENT mesec (#PCDATA)>
    <!ELEMENT godina (#PCDATA)>
  <!ELEMENT adresa (ulica, broj, grad, drzava?)>
    <!ELEMENT ulica (#PCDATA)>
    <!ELEMENT broj (#PCDATA)>
    <!ELEMENT grad (#PCDATA)>
    <!ELEMENT drzava (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT email (#PCDATA)>

<!ELEMENT kompanija (naziv, adresa, telefon, email+)>
<!ELEMENT naziv (#PCDATA)>

<!ATTLIST osoba osobaID ID #REQUIRED>
<!ATTLIST adresa tip (privremena | stalna) "privremena">
<!ATTLIST telefon tip (fiksni | mobilni) #REQUIRED>
<!ATTLIST email tip (privatni | sluzbeni) #REQUIRED>
<!ATTLIST kompanija kompanijaID ID #REQUIRED>






<!--<!ELEMENT magacin (artikal+)>
<!ELEMENT artikal (naziv, kategorija, cena, dobavljač)>
<!ELEMENT naziv (#PCDATA)>
<!ELEMENT kategorija (opis)>
<!ELEMENT opis (#PCDATA | datumProizvodnje | marka )*>
<!ELEMENT datumProizvodnje (#PCDATA)>
<!ELEMENT marka (#PCDATA)>

<!ELEMENT cena (#PCDATA)>
<!ELEMENT dobavljač (dnaziv, adresa, grad, država?, telefon?)>
 <!ELEMENT dnaziv (#PCDATA)>
 <!ELEMENT adresa (#PCDATA)>
 <!ELEMENT grad (#PCDATA)>
 <!ELEMENT država (#PCDATA)>
 <!ELEMENT telefon (#PCDATA)>
 
<!ATTLIST artikal 
                      stanje  (otpisano | važeće) #REQUIRED
                      jedinicaMere (kom | kg) #IMPLIED
                      količina CDATA #IMPLIED>
  <!ATTLIST naziv skraćenica (da | ne) #REQUIRED>
  <!ATTLIST kategorija idKategorije ID #REQUIRED>
  <!ATTLIST cena valuta (RSD | EUR | USD) "RSD">
<!ATTLIST telefon tip (mobilni | fiksni) #IMPLIED>-->

=== c1ra/xmlDemo/XMLFile2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE adresar SYSTEM "dtd2.dtd">
<adresar xmlns="http://cira.com/defoultNS">
  <osoba osobaID="O12" >
    <punoIme>
      <ime>Petar</ime>
      <srednjeIme>DrvoIzmena</srednjeIme>
      <prezime>Peric</prezime>
    </punoIme>
    <datumRodjenja>
      <dan>12</dan>
      <mesec>3</mesec>
      <godina>1993</godina>
    </datumRodjenja>
    <adresa tip="privremena">
      <ulica>Kralja Petra Izmena2</ulica>
      <broj>2</broj>
      <grad>Beograd</grad>
    </adresa>
    <telefon tip="fiksni">011223335</telefon>
    <email tip="privatni">blabla@gmail.com</email>
  </osoba>
  <kompanija kompanijaID="K12">
    <naziv>Pera DOO</naziv>
    <adresa>
      <ulica>Brace Jerkovic</ulica>
      <broj>71</broj>
      <grad>Beograd</grad>
      <drzava>Srbija</drzava>
    </adresa>
    <telefon tip="mobilni">063/133-325</telefon>
    <email tip ="sluzbeni">bla2bla2@gmail.com</email>
    <email tip ="sluzbeni">bla2bla2Company@gmail.com</email>
  </kompanija>
</adresar>
